In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(object=list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
#Yes there is a difference between datatypes of list_ and array_list

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [12]:
for i in list_:    
	print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for i in array_list:
	print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable,
#### array_list: array_list = np.array(object = list_, dtype = int) 

#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [17]:
array_list = np.array(object = list_, dtype = int)

In [18]:
array_list.dtype

dtype('int32')

In [19]:
array_list

array([1, 2, 3, 4, 5])

There will be change in the data type of the array_list but not in the data type of list_ variable.

In [22]:
for i in array_list:
	print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Consider the below code to answer further questions:

In [23]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [27]:
mat=np.zeros((3,3))

In [28]:
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
mat.size

9

In [30]:
mat.shape

(3, 3)

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [31]:
i=np.eye(5)

In [32]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])